### ISSUE TITLE
azdev extension list not work

### ISSUE THREAD

**Issue by Juliehzl** [Azure/azure-cli-dev-tools#116] opened 2019-07-24 08:10 UTC
azdev version: 0.1.4
python version: 3.7.4 64 bit
OS: Windows 10

When I run ```azdev extension list```, [] is returned. But I have installed storage-preview extension.

**Comment by tjprescott** [comment] 2019-07-24 20:57
When you run `az --version` does it show storage installed as a dev extension or regular? `azdev extension list` only shows extensions installed in dev mode by azdev itself.

**Comment by Juliehzl** [comment] 2019-07-25 01:23
Yes, with ```az --version``` I can see the extension installed.
There are two questions about azure-cli-extensions:
1.  If I want to upgrade or uninstall a regular extension, what should I do?  Delete files manually or something else?

2. How can I decide to install the extension in dev mode or regular mode?

**Comment by tjprescott** [comment] 2019-07-25 15:52
Anything you do with `azdev extension` is in dev mode. Any extension you install using `az extension` will be invisible to azdev. Any extension you install in regular mode will override any dev-installed extension. So if you want to upgrade or install a regular extension, you can just do so using `az extension add/update`.  Since this is working as intended, I will close.

**Closed by tjprescott** 2019-07-25 15:52 UTC
Labels: Extension
