### ISSUE TITLE
az test not working and can't use debugger 

### ISSUE THREAD

**Issue by ziwa-msft** [Azure/azure-cli-dev-tools#78] opened 2019-05-06 22:17 UTC
cli_ctx = <azure.cli.core.mock.DummyCli object at 0x0000000006DFA6A0>
command = 'sql instance-failover-group create --instance-failover-group-name fgclitest2019 -g geodrCLtestRG --managed-instance-n...-resource-group geodrCLtestRG --partner-managed-instance geodrmitestgp-02 --failover-policy Automatic
--grace-period 2'
expect_failure = False

    def _in_process_execute(self, cli_ctx, command, expect_failure=False):
        from six import StringIO
        from vcr.errors import CannotOverwriteExistingCassetteException
    
        if command.startswith('az '):
            command = command[3:]
        print shlex.split(command)
    
        stdout_buf = StringIO()
        logging_buf = StringIO()
        try:
            # issue: stderr cannot be redirect in this form, as a result some failure information
            # is lost when command fails.
            self.exit_code = cli_ctx.invoke(shlex.split(command), out_file=stdout_buf) or 0
            self.output = stdout_buf.getvalue()
            self.applog = logging_buf.getvalue()
    
        except CannotOverwriteExistingCassetteException as ex:
            raise AssertionError(ex)
        except CliExecutionError as ex:
            if expect_failure:
                self.exit_code = 1
                self.output = stdout_buf.getvalue()
                self.applog = logging_buf.getvalue()
            elif ex.exception:
                print ex.message
                print stdout_buf.getvalue()
>               raise ex.exception
E               TypeError: __init__() takes exactly 1 argument (3 given)

src\azure-cli-testsdk\azure\cli\testsdk\base.py:265: TypeError
---------------------------- Captured stdout call -----------------------------
['sql', 'mi', 'show', '-g', 'geodrCLtestRG', '-n', 'geodrmitestgp-01']
['sql', 'mi', 'show', '-g', 'geodrCLtestRG', '-n', 'geodrmitestgp-02']
['sql', 'instance-failover-group', 'create', '--instance-failover-group-name', 'fgclitest2019', '-g', 'geodrCLtestRG', '--managed-instance-name', 'geodrmitestgp-01', '--partner-resource-group', 'geodrCLtestRG', '--partner-managed-instance', 'geodrmitestgp-02', '--failover-policy', 'Automatic', '--grace-period', '2']
The CLI throws exception TypeError during execution and fails the command.

- generated xml file: C:\Users\ziwa\.azdev\env_config\azure-cli\env3\test_results.xml -
========================== 1 failed in 7.25 seconds ===========================

When I was trying to set debuggers with launch.json set to the azdev test cmd, I got:

az: 'azdev test SqlInstanceFailoverGroupMgmtScenarioTest --live' is not in the 'az' command group. See 'az --help'.

**Comment by tjprescott** [comment] 2019-05-06 23:12
I'm not sure what you are trying to debug into. If you are trying to debug into your test, you need to run your test from the Visual Studio debugger. It has nothing to do with azdev.

Does your command run locally correctly?

**Comment by ziwa-msft** [comment] 2019-05-06 23:49
nope the cmd didn't run locally as well. hitting the same error:

(env3) F:\azure-cli>az sql instance-failover-group create --instance-failover-group-name fgclitest2019 -g geodrCLtestRG
The command failed with an unexpected error. Here is the traceback:

__init__() takes exactly 1 argument (3 given)
Traceback (most recent call last):
  File "F:\azure-cli\env3\lib\site-packages\knack\cli.py", line 207, in invoke
    cmd_result = self.invocation.execute(args)
  File "f:\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 523, in execute
    raise ex
TypeError: __init__() takes exactly 1 argument (3 given)

Any idea on how to debug this? 

Thanks a lot,
MIke

**Comment by tjprescott** [comment] 2019-05-07 15:18
Right, if the command doesn't run locally, then the problem is in your command, not azdev. If you want to debug into a test, you need to open the VS solution file for azure-cli or azure-cli-extensions and debug into it that way. However, the best approach would simply be to debug into a local execution of the command instead of the test. It is faster.

Since this is not a problem with azdev test, I will close this.

**Closed by tjprescott** 2019-05-07 15:18 UTC
Labels: Test, question
